# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTcyZmY5NGQ0MDQ5YWQxMTJiNzZiOTk0YTJmYjgwNTA1NTZmY2MzYzQ0OTJmM2VmZjNkNzI1ZGRhZmNiYjBjYjBjMWZjNjRhNTRmY2NiMjI0MDhiMjZiZGI1YWVhZTZlYTg2Njc4NTc3ZGQyNWE3MDdjYTY2MjZjNmZkMmZlZDM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
